sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:
  - ARCH="x86_64"

matrix:
  include:
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}

before_install:
  - sudo apt-get install -qq python-numpy
  - cd test && python test_npy_fileio.py && cd ..
  # https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt-get update
  - sudo apt-cache search mkl
  - MKL_VER=
  - if [ $ARCH = "x86_64" ]; then
      sudo apt-get install -qq intel-mkl-core-rt-2018.1-163;
      /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/compilervars.sh intel64;
    else
      sudo apt-get install -qq intel-mkl-core-rt-32bit-2018.1-163;
      /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/compilervars.sh ia32;
    fi    

script:
  - dub test --arch "$ARCH" --build=unittest-cov
  - export OMP_NUM_THREADS=1
  - cd example/char_rnn && dub run --arch "$ARCH" --build=release && cd -
  - cd example/audio_separation && dub run --arch "$ARCH" --build=release && cd -
  # https://github.com/vibe-d/vibe.d/blob/master/README.md#additional-setup-on-linux-debianubuntumint
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then sudo apt-get install -qq libevent-dev libssl-dev; fi
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then make doc; fi
  # https://github.com/blog/572-bypassing-jekyll-on-github-pages
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then touch docs/.nojekyll; fi

after_success:
 - bash <(curl -s https://codecov.io/bash)

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: $DC = dmd && $ARCH = "x86_64"
